import 'package:flutter/material.dart';

class AppStrings {
  // English Translations
  static const Map<String, String> en = {
    'app_name': 'Anticrash',
    'login_title': 'Login',
    'login_subtitle': 'Sign in to continue',
    'create_account': 'Create Account',
    'name': 'Name',
    'email': 'Email',
    'phone': 'Phone',
    'address': 'Address',
    'location': 'Location',
    'get_location': 'Get Location',
    'location_fetching': 'Fetching location...',
    'error_location_empty': 'Please get your location',
    'error_location_services_disabled': 'Location services are disabled',
    'error_location_permission_denied': 'Location permission was denied',
    'error_location_permission_denied_forever':
        'Location permission is permanently denied',
    'error_location_failed': 'Failed to get location',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'machine_type': 'Machine Type',
    'machine_serial': 'Machine Serial',
    'machine_ownership': 'Machine Ownership',
    'ownership_owner': 'Owner',
    'ownership_rent': 'Rent',
    'select_representative': 'Select Distributor',
    'representatives': 'Distributors',
    'loading_representatives': 'Loading distributors...',
    'no_representatives': 'No distributors available',
    'customer_orders': 'Customer Orders',
    'customer_notifications': 'Customer Notifications',
    'invoices': 'Invoices',
    'location_required': 'Location permission is required for representatives.',
    'login_button': 'Login',
    'register_button': 'Register',
    'register_now': 'Don\'t have an account? Register',
    'already_have_account': 'Already have an account? Login',
    'error_name_length': 'Name must be at least 3 characters',
    'error_email_empty': 'Please enter an email',
    'error_email_invalid': 'Please enter a valid email',
    'error_phone_empty': 'Please enter a phone number',
    'error_address_empty': 'Please enter an address',
    'error_password_length': 'Password must be at least 8 characters',
    'error_password_match': 'Passwords do not match',
    'error_representative_required': 'Please select a distributor',
    'error_generic': 'An error occurred',
    'language': 'Language',
    'english': 'English',
    'arabic': 'Arabic',
    'logout_title': 'Logout',
    'logout_confirm': 'Are you sure you want to logout?',
    'cancel': 'Cancel',
    'profile': 'Profile',
    'remaining_pieces': 'Remaining Pieces',
    'guest': 'Guest',
    'logout': 'Logout',
    'home': 'Home',
    'categories': 'Categories',
    'remaining': 'Remaining',
    'connect_cutter': 'Connect Cutter',
    'no_categories': 'No Categories Found',
    'status_ready': 'Ready',
    'status_downloading': 'Downloading file...',
    'status_no_file': 'No file available',
    'status_file_ready': 'File Ready',
    'status_download_failed': 'Download Failed',
    'error_not_enough_pieces': 'Error: Not enough pieces left to cut.',
    'status_verifying_balance': 'Verifying Balance...',
    'status_sync_handshake': 'Synchronizing Handshake...',
    'error_handshake_failed': 'Handshake synchronization failed.',
    'status_init_cut': 'Initializing Cut...',
    'status_clearing_buffer': 'Clearing Buffer...',
    'status_homing': 'Homing...',
    'status_sending_data': 'Sending Data...',
    'status_starting_cut': 'Starting Cut...',
    'status_cut_started': 'Cut Started!',
    'msg_cut_success': 'Cut Started Successfully!',
    'cutter_control_title': 'Cutter Control',
    'unknown_product': 'Unknown Product',
    'send_to_cutter': 'SEND TO CUTTER',
    'connect_to_cutter': 'CONNECT TO CUTTER',
    'not_enough_pieces': 'NOT ENOUGH PIECES',
    'permissions_required': 'Permissions required for Bluetooth scanning',
    'disconnect_to_scan': 'Please disconnect from the current device to scan.',
    'connecting': 'Connecting...',
    'authenticating': 'Authenticating...',
    'connected_authenticated': 'Connected & Authenticated!',
    'auth_failed': 'Authentication Failed',
    'connection_error': 'Connection Error',
    'select_machine': 'Select Machine',
    'msg_disconnect_to_scan': 'Disconnect to scan',
    'scanning': 'Scanning...',
    'found_devices': 'Found devices',
    'unknown_device': 'Unknown Device',
    'hold_to_test_handshake': 'Press and hold to test Handshake',
    'status_connected': 'Connected',
    'grant_bluetooth_permission':
        'Please grant Bluetooth permissions in settings to scan for machines.',
    'bluetooth_perms_required': 'Bluetooth Permissions Required',
    'bluetooth_is_off': 'Bluetooth is Off',
    'turn_on_bluetooth_msg':
        'Please turn on Bluetooth to scan for available cutting machines.',
    'turn_on_bluetooth_btn': 'Turn On Bluetooth',
    'connect_required_title': 'Machine Connection Required',
    'connect_required_msg':
        'You must connect to the cutter through the internal serial port to access categories.',
    'go_to_connect': 'Go to Connect',
    'search_hint': 'Search Categories or Products...',
    'request_rep': 'Request Representative',
    'no_rep_found': 'No representative associated with the account.',
    'rep_notification_msg':
        'A notification will be sent to the representative: ',
    'notification_sent': 'Notification sent successfully!',
    'send': 'Send',
    'attachments': 'Attachments',
    'cut_settings': 'Cut Settings',
    'system_information': 'System Information',
    'system_refresh': 'Refresh',
    'system_not_connected': 'Please connect to the cutter first.',
    'system_pg_head': 'PG Head',
    'system_device_model': 'Device Model',
    'system_app_version': 'App Version',
    'system_software_version': 'Software Version',
    'system_hardware_version': 'Hardware Version',
    'system_unique_id': 'Unique ID',
    'system_fault_code': 'Fault Code',
    'system_server_connection': 'Server Connection',
    'system_server_normal': 'Normal',
    'system_server_failure': 'Failure',
    'system_device_number': 'Device Number',
    'system_email_account': 'Email Account',
    'system_unknown': 'Unknown',
    'app_update': 'App Update',
    'installed_version': 'Installed version: {version}',
    'auto_update': 'Automatic Update',
    'check_for_update': 'Update Now',
    'update_checking': 'Checking for update...',
    'update_downloading': 'Downloading update...',
    'update_no_new_version': 'This device is already on the latest version.',
    'update_ready_installing': 'Installing update silently...',
    'update_started_background':
        'Update started in the background. The app will reopen after installation.',
    'update_completed_silent': 'Update installed successfully.',
    'update_failed': 'Automatic update failed: {message}',
    'update_invalid_manifest': 'The server version file is invalid.',
    'update_apk_not_newer':
        'The downloaded update APK is not newer than the installed version.',
    'speed': 'Speed',
    'pressure': 'Pressure',
    'auto_feed': 'Automatic Paper Feed',
    'force_landscape': 'Force Landscape',
    'set_angle': 'Set Angle',
    'set_angle_title': 'Set Angle',
    'angle_hint': '-45 to 45',
    'angle_display': 'Angle: {value}',
    'led_brightness': 'LED Brightness',
    'single_test_cut_label': 'Single Test Cut',
    'cutting_test': 'Cutting Test',
    'sent_test_cut_command': 'Test cut command sent.',
    'test_sequence_sent': 'Test sequence sent.',
    'request_machine_info': 'Request Machine Info',
    'requested_machine_info': 'Machine info requested.',
    'error_connect_to_cutter': 'Please connect to cutter first.',
    'order_info': 'Order Information',
    'customer': 'Customer',
    'representative': 'Representative',
    'your_selected_products': 'Your Selected Products',
    'set_quantity': 'Set Quantity',
    'price': 'Price',
    'delete': 'Delete',
    'save': 'Save',
    'order_success': 'Order Successful',
    'order_success_msg':
        'Your order has been sent successfully. We will contact you soon.',
    'search_product_hint': 'Search for product...',
    'products': 'Products',
    'page_of': 'Page {page} of {total}',
    'currency_jod': 'JOD',
    'product_details': 'Product Details',
    'product_not_found': 'Product not found',
    'discount': 'Discount',
    'available_stock': 'Available Stock',
    'pieces': 'Pieces',
    'available': 'Available',
    'out_of_stock': 'Out of Stock',
    'description': 'Description',
    'quantity': 'Quantity',
    'ok': 'OK',
    'load_more': 'Load More',
    'total_amount': 'Total Amount',
    'no_products_available': 'No products available',
    'not_added': 'Not Added',
    'stock_available': 'Stock: ',
    'matching_categories': 'Matching Categories',
    'matching_products': 'Matching Products',
    'no_matching_categories': 'No matching categories found',
    'no_products_found': 'No products found',
    'product_label': 'Product',
    'filter_all': 'All',
    'filter_back': 'Back',
    'filter_front': 'Front',
    'no_items_found': 'No items found',
    'select_button': 'SELECT',
    'search_in_category': 'Search {category}...',
  };

  // Arabic Translations
  static const Map<String, String> ar = {
    'app_name': 'Anticrash',
    'login_title': 'تسجيل الدخول',
    'login_subtitle': 'سجل الدخول للمتابعة',
    'create_account': 'إنشاء حساب',
    'name': 'الاسم',
    'email': 'البريد الإلكتروني',
    'phone': 'رقم الهاتف',
    'address': 'العنوان',
    'password': 'كلمة المرور',
    'confirm_password': 'تأكيد كلمة المرور',
    'machine_type': 'نوع الماكينة',
    'machine_serial': 'سيريال الماكينة',
    'machine_ownership': 'ملكية الماكينة',
    'ownership_owner': 'ملك',
    'ownership_rent': 'إجار',
    'select_representative': 'اختيار الموزع',
    'representatives': 'الموزعون',
    'loading_representatives': 'جاري تحميل الموزعين...',
    'no_representatives': 'لا يوجد موزعون متاحون',
    'customer_orders': 'طلبات الزبائن',
    'customer_notifications': 'إشعارات الزبائن',
    'invoices': 'فواتير',
    'location_required': 'يلزم السماح بالموقع للمندوب.',
    'login_button': 'دخول',
    'register_button': 'تسجيل',
    'register_now': 'ليس لديك حساب؟ سجل الآن',
    'already_have_account': 'لديك حساب بالفعل؟ سجل الدخول',
    'error_name_length': 'الاسم يجب أن يكون 3 أحرف على الأقل',
    'error_email_empty': 'الرجاء إدخال البريد الإلكتروني',
    'error_email_invalid': 'البريد الإلكتروني غير صالح',
    'error_phone_empty': 'الرجاء إدخال رقم الهاتف',
    'error_address_empty': 'الرجاء إدخال العنوان',
    'error_password_length': 'كلمة المرور يجب أن تكون 8 أحرف على الأقل',
    'error_password_match': 'كلمات المرور غير متطابقة',
    'error_representative_required': 'الرجاء اختيار الموزع',
    'error_generic': 'حدث خطأ ما',
    'language': 'اللغة',
    'english': 'English',
    'arabic': 'العربية',
    'logout_title': 'تسجيل الخروج',
    'logout_confirm': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
    'cancel': 'إلغاء',
    'profile': 'الملف الشخصي',
    'remaining_pieces': 'القطع المتبقية',
    'guest': 'زائر',
    'logout': 'خروج',
    'home': 'الرئيسية',
    'categories': 'التصنيفات',
    'remaining': 'المتبقي',
    'connect_cutter': 'اتصل بماكنة القص',
    'no_categories': 'لا يوجد تصنيفات',
    'status_ready': 'جاهز',
    'status_downloading': 'جاري تحميل الملف...',
    'status_no_file': 'لا يوجد ملف',
    'status_file_ready': 'الملف جاهز',
    'status_download_failed': 'فشل التحميل',
    'error_not_enough_pieces': 'خطأ: لا يوجد رصيد كافي للقص.',
    'status_verifying_balance': 'جاري التحقق من الرصيد...',
    'status_sync_handshake': 'جاري المزامنة...',
    'error_handshake_failed': 'فشلت المزامنة.',
    'status_init_cut': 'جاري تهيئة القص...',
    'status_clearing_buffer': 'جاري تنظيف الذاكرة...',
    'status_homing': 'العودة للصفر...',
    'status_sending_data': 'جاري إرسال البيانات...',
    'status_starting_cut': 'جاري بدء القص...',
    'status_cut_started': 'بدأ القص!',
    'msg_cut_success': 'تم بدء القص بنجاح!',
    'cutter_control_title': 'التحكم في ماكنة القص',
    'unknown_product': 'منتج غير معروف',
    'send_to_cutter': 'إرسال للقاطع',
    'connect_to_cutter': 'اتصل بماكنة القص',
    'not_enough_pieces': 'الرصيد غير كافي',
    'permissions_required': 'يلزم الحصول على أذونات لعمل مسح للبلوتوث',
    'disconnect_to_scan': 'الرجاء فصل الجهاز الحالي للبدء بالبحث',
    'connecting': 'جاري الاتصال...',
    'authenticating': 'جاري المصادقة...',
    'connected_authenticated': 'تم الاتصال والمصادقة بنجاح!',
    'auth_failed': 'فشلت المصادقة',
    'connection_error': 'خطأ في الاتصال',
    'select_machine': 'اختر الجهاز',
    'msg_disconnect_to_scan': 'افصل الجهاز للبحث',
    'scanning': 'جاري البحث...',
    'found_devices': 'تم العثور على أجهزة',
    'unknown_device': 'جهاز غير معروف',
    'hold_to_test_handshake': 'اضغط مطولاً لاختبار المصافحة',
    'status_connected': 'متصل',
    'grant_bluetooth_permission':
        'الرجاء منح أذونات البلوتوث في الإعدادات للبحث عن الأجهزة.',
    'bluetooth_perms_required': 'أذونات البلوتوث مطلوبة',
    'bluetooth_is_off': 'البلوتوث مغلق',
    'turn_on_bluetooth_msg': 'الرجاء تشغيل البلوتوث للبحث عن القواطع المتاحة.',
    'turn_on_bluetooth_btn': 'تشغيل البلوتوث',
    'connect_required_title': 'يلزم الاتصال بالماكينة',
    'connect_required_msg':
        'يجب الاتصال بماكينة القص عبر المنفذ التسلسلي الداخلي للوصول إلى التصنيفات.',
    'go_to_connect': 'الذهاب للاتصال',
    'search_hint': 'بحث عن تصنيفات أو منتجات...',
    'request_rep': 'طلب مندوب',
    'no_rep_found': 'لا يوجد مندوب مرتبط بالحساب.',
    'rep_notification_msg': 'سيتم إرسال تنبيه إلى المندوب: ',
    'notification_sent': 'تم إرسال التنبيه بنجاح!',
    'send': 'إرسال',
    'attachments': 'ملحقات',
    'cut_settings': 'إعدادات القص',
    'app_update': 'تحديث التطبيق',
    'installed_version': 'الإصدار المثبت: {version}',
    'auto_update': 'تحديث تلقائي',
    'check_for_update': 'تحديث الآن',
    'update_checking': 'جارٍ التحقق من التحديث...',
    'update_downloading': 'جارٍ تنزيل التحديث...',
    'update_no_new_version': 'الجهاز يعمل على آخر إصدار بالفعل.',
    'update_ready_installing': 'جارٍ تثبيت التحديث بصمت...',
    'update_started_background':
        'بدأ التحديث في الخلفية. سيُعاد فتح التطبيق بعد انتهاء التثبيت.',
    'update_completed_silent': 'تم تثبيت التحديث بنجاح.',
    'update_failed': 'فشل التحديث التلقائي: {message}',
    'update_invalid_manifest': 'ملف نسخة السيرفر غير صالح.',
    'update_apk_not_newer':
        'ملف التحديث الذي تم تنزيله ليس أحدث من الإصدار المثبت.',
    'order_info': 'بيانات الطلب',
    'customer': 'الزبون',
    'representative': 'المندوب',
    'your_selected_products': 'منتجاتك المختارة',
    'set_quantity': 'تحديد الكمية',
    'price': 'السعر',
    'delete': 'حذف',
    'save': 'حفظ',
    'order_success': 'طلب ناجح',
    'order_success_msg': 'تم إرسال طلبك بنجاح سيتم التواصل معك قريباً.',
    'search_product_hint': 'بحث عن منتج...',
    'products': 'المنتجات',
    'page_of': 'صفحة {page} من {total}',
    'force_landscape': 'إجباري أفقي',
    'currency_jod': 'د.أ',
    'product_details': 'تفاصيل المنتج',
    'product_not_found': 'لم يتم العثور على المنتج',
    'discount': 'خصم',
    'available_stock': 'المخزون المتاح',
    'pieces': 'قطعة',
    'available': 'متوفر',
    'out_of_stock': 'غير متوفر',
    'description': 'الوصف',
    'quantity': 'الكمية',
    'ok': 'حسناً',
    'load_more': 'تحميل المزيد',
    'total_amount': 'المجموع الكلي',
    'no_products_available': 'لا توجد منتجات متاحة',
    'not_added': 'لم يتم الإضافة',
    'stock_available': 'المتوفر المتاح: ',
    'matching_categories': 'تصنيفات مطابقة',
    'matching_products': 'منتجات مطابقة',
    'no_matching_categories': 'لم يتم العثور على تصنيفات مطابقة',
    'no_products_found': 'لم يتم العثور على منتجات',
    'product_label': 'منتج',
    'filter_all': 'الكل',
    'filter_back': 'خلفي',
    'filter_front': 'أمامي',
    'no_items_found': 'لم يتم العثور على عناصر',
    'select_button': 'اختيار',
    'search_in_category': 'بحث في {category}...',
  };

  // Helper to get string based on language code
  static String get(String key, String langCode) {
    if (langCode == 'ar') {
      return ar[key] ?? en[key] ?? key;
    }
    return en[key] ?? key;
  }

  // Easy access via context
  static String of(BuildContext context, String key) {
    final Locale locale = Localizations.localeOf(context);
    return get(key, locale.languageCode);
  }
}
