import 'package:flutter/material.dart';

class AppStrings {
  // English Translations
  static const Map<String, String> en = {
    'app_name': 'Anticrash Cutter',
    'login_title': 'Login',
    'login_subtitle': 'Sign in to continue',
    'create_account': 'Create Account',
    'name': 'Name',
    'email': 'Email',
    'phone': 'Phone',
    'address': 'Address',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'login_button': 'Login',
    'register_button': 'Register',
    'register_now': 'Don\'t have an account? Register',
    'already_have_account': 'Already have an account? Login',
    'error_name_length': 'Name must be at least 3 characters',
    'error_email_empty': 'Please enter an email',
    'error_email_invalid': 'Please enter a valid email',
    'error_phone_empty': 'Please enter a phone number',
    'error_address_empty': 'Please enter an address',
    'error_password_length': 'Password must be at least 8 characters',
    'error_password_match': 'Passwords do not match',
    'error_generic': 'An error occurred',
    'language': 'Language',
    'english': 'English',
    'arabic': 'Arabic',
    'logout_title': 'Logout',
    'logout_confirm': 'Are you sure you want to logout?',
    'cancel': 'Cancel',
    'profile': 'Profile',
    'remaining_pieces': 'Remaining Pieces',
    'guest': 'Guest',
    'logout': 'Logout',
    'home': 'Home',
    'categories': 'Categories',
    'remaining': 'Remaining',
    'connect_cutter': 'Connect Cutter',
    'no_categories': 'No Categories Found',
    'status_ready': 'Ready',
    'status_downloading': 'Downloading file...',
    'status_no_file': 'No file available',
    'status_file_ready': 'File Ready',
    'status_download_failed': 'Download Failed',
    'error_not_enough_pieces': 'Error: Not enough pieces left to cut.',
    'status_verifying_balance': 'Verifying Balance...',
    'status_sync_handshake': 'Synchronizing Handshake...',
    'error_handshake_failed': 'Handshake synchronization failed.',
    'status_init_cut': 'Initializing Cut...',
    'status_clearing_buffer': 'Clearing Buffer...',
    'status_homing': 'Homing...',
    'status_sending_data': 'Sending Data...',
    'status_starting_cut': 'Starting Cut...',
    'status_cut_started': 'Cut Started!',
    'msg_cut_success': 'Cut Started Successfully!',
    'cutter_control_title': 'Cutter Control',
    'unknown_product': 'Unknown Product',
    'send_to_cutter': 'SEND TO CUTTER',
    'connect_to_cutter': 'CONNECT TO CUTTER',
    'not_enough_pieces': 'NOT ENOUGH PIECES',
    'permissions_required': 'Permissions required for Bluetooth scanning',
    'disconnect_to_scan': 'Please disconnect from the current device to scan.',
    'connecting': 'Connecting...',
    'authenticating': 'Authenticating...',
    'connected_authenticated': 'Connected & Authenticated!',
    'auth_failed': 'Authentication Failed',
    'connection_error': 'Connection Error',
    'select_machine': 'Select Machine',
    'msg_disconnect_to_scan': 'Disconnect to scan',
    'scanning': 'Scanning...',
    'found_devices': 'Found devices',
    'unknown_device': 'Unknown Device',
    'hold_to_test_handshake': 'Press and hold to test Handshake',
    'status_connected': 'Connected',
    'grant_bluetooth_permission':
        'Please grant Bluetooth permissions in settings to scan for machines.',
    'bluetooth_perms_required': 'Bluetooth Permissions Required',
    'bluetooth_is_off': 'Bluetooth is Off',
    'turn_on_bluetooth_msg':
        'Please turn on Bluetooth to scan for available cutting machines.',
    'turn_on_bluetooth_btn': 'Turn On Bluetooth',
  };

  // Arabic Translations
  static const Map<String, String> ar = {
    'app_name': 'Anticrash Cutter',
    'login_title': 'تسجيل الدخول',
    'login_subtitle': 'سجل الدخول للمتابعة',
    'create_account': 'إنشاء حساب',
    'name': 'الاسم',
    'email': 'البريد الإلكتروني',
    'phone': 'رقم الهاتف',
    'address': 'العنوان',
    'password': 'كلمة المرور',
    'confirm_password': 'تأكيد كلمة المرور',
    'login_button': 'دخول',
    'register_button': 'تسجيل',
    'register_now': 'ليس لديك حساب؟ سجل الآن',
    'already_have_account': 'لديك حساب بالفعل؟ سجل الدخول',
    'error_name_length': 'الاسم يجب أن يكون 3 أحرف على الأقل',
    'error_email_empty': 'الرجاء إدخال البريد الإلكتروني',
    'error_email_invalid': 'البريد الإلكتروني غير صالح',
    'error_phone_empty': 'الرجاء إدخال رقم الهاتف',
    'error_address_empty': 'الرجاء إدخال العنوان',
    'error_password_length': 'كلمة المرور يجب أن تكون 8 أحرف على الأقل',
    'error_password_match': 'كلمات المرور غير متطابقة',
    'error_generic': 'حدث خطأ ما',
    'language': 'اللغة',
    'english': 'English',
    'arabic': 'العربية',
    'logout_title': 'تسجيل الخروج',
    'logout_confirm': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
    'cancel': 'إلغاء',
    'profile': 'الملف الشخصي',
    'remaining_pieces': 'القطع المتبقية',
    'guest': 'زائر',
    'logout': 'خروج',
    'home': 'الرئيسية',
    'categories': 'التصنيفات',
    'remaining': 'المتبقي',
    'connect_cutter': 'اتصل بماكنة القص',
    'no_categories': 'لا يوجد تصنيفات',
    'status_ready': 'جاهز',
    'status_downloading': 'جاري تحميل الملف...',
    'status_no_file': 'لا يوجد ملف',
    'status_file_ready': 'الملف جاهز',
    'status_download_failed': 'فشل التحميل',
    'error_not_enough_pieces': 'خطأ: لا يوجد رصيد كافي للقص.',
    'status_verifying_balance': 'جاري التحقق من الرصيد...',
    'status_sync_handshake': 'جاري المزامنة...',
    'error_handshake_failed': 'فشلت المزامنة.',
    'status_init_cut': 'جاري تهيئة القص...',
    'status_clearing_buffer': 'جاري تنظيف الذاكرة...',
    'status_homing': 'العودة للصفر...',
    'status_sending_data': 'جاري إرسال البيانات...',
    'status_starting_cut': 'جاري بدء القص...',
    'status_cut_started': 'بدأ القص!',
    'msg_cut_success': 'تم بدء القص بنجاح!',
    'cutter_control_title': 'التحكم في ماكنة القص',
    'unknown_product': 'منتج غير معروف',
    'send_to_cutter': 'إرسال للقاطع',
    'connect_to_cutter': 'اتصل بماكنة القص',
    'not_enough_pieces': 'الرصيد غير كافي',
    'permissions_required': 'يلزم الحصول على أذونات لعمل مسح للبلوتوث',
    'disconnect_to_scan': 'الرجاء فصل الجهاز الحالي للبدء بالبحث',
    'connecting': 'جاري الاتصال...',
    'authenticating': 'جاري المصادقة...',
    'connected_authenticated': 'تم الاتصال والمصادقة بنجاح!',
    'auth_failed': 'فشلت المصادقة',
    'connection_error': 'خطأ في الاتصال',
    'select_machine': 'اختر الجهاز',
    'msg_disconnect_to_scan': 'افصل الجهاز للبحث',
    'scanning': 'جاري البحث...',
    'found_devices': 'تم العثور على أجهزة',
    'unknown_device': 'جهاز غير معروف',
    'hold_to_test_handshake': 'اضغط مطولاً لاختبار المصافحة',
    'status_connected': 'متصل',
    'grant_bluetooth_permission':
        'الرجاء منح أذونات البلوتوث في الإعدادات للبحث عن الأجهزة.',
    'bluetooth_perms_required': 'أذونات البلوتوث مطلوبة',
    'bluetooth_is_off': 'البلوتوث مغلق',
    'turn_on_bluetooth_msg': 'الرجاء تشغيل البلوتوث للبحث عن القواطع المتاحة.',
    'turn_on_bluetooth_btn': 'تشغيل البلوتوث',
  };

  // Helper to get string based on language code
  static String get(String key, String langCode) {
    if (langCode == 'ar') {
      return ar[key] ?? en[key] ?? key;
    }
    return en[key] ?? key;
  }

  // Easy access via context
  static String of(BuildContext context, String key) {
    final Locale locale = Localizations.localeOf(context);
    return get(key, locale.languageCode);
  }
}
